name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Этот этап будет выполняться только если все тесты успешно прошли
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Create .ssh directory
      run: |
        mkdir -p /home/kulich/.ssh
        chmod 700 /home/kulich/.ssh

    - name: Ensure HOME is set
      run: |
        echo "HOME is set to $HOME"
        export HOME=/home/kulich
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

    - name: Debug environment
      run: |
        echo "Current user: $(whoami)"
        echo "Home directory: $HOME"
        ls -ld $HOME

    - name: Create .ssh directory with sudo
      run: |
        sudo mkdir -p ~/.ssh
        sudo chmod 700 ~/.ssh

    - name: Debug SSH Setup
      run: |
        mkdir -p ~/.ssh || echo "Error in mkdir"
        chmod 700 ~/.ssh || echo "Error in chmod"
        echo "***" > ~/.ssh/id_rsa || echo "Error in creating id_rsa"
        chmod 600 ~/.ssh/id_rsa || echo "Error in chmod id_rsa"
        ssh-keyscan -H 172.22.4.126 >> ~/.ssh/known_hosts || echo "Error in ssh-keyscan"

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H 172.22.4.126 >> ~/.ssh/known_hosts
      shell: bash

    - name: Deploy to server
      run: |
        ssh -o StrictHostKeyChecking=no git@github.com << EOF
          cd //wsl.localhost/Ubuntu/home/kulich/mortgage_calculator &&
          git pull origin main &&
          systemctl restart your_service
        EOF

    - name: Debug SSH
      run: |
        whoami
        ls -ld ~/.ssh
        echo "Contents of ~/.ssh:"
        ls -la ~/.ssh
    
