name: Python CI/CD

on:
  push:
    branches:
      - main
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/deploy'
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -T -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no kulich@localhost << 'EOF'
        cd //wsl.localhost/Ubuntu/home/kulich/mortgage_calculator &&
        git pull origin main &&
        systemctl restart your_service
        EOF
