name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Выполняется только после успешного прохождения этапа build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        # Создание директории для SSH-ключей
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # Установка секретного ключа
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Добавление хоста в known_hosts
        ssh-keyscan -H 172.22.4.126 >> ~/.ssh/known_hosts

        # Проверка содержимого .ssh для отладки
        ls -la ~/.ssh

    - name: Deploy to server
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        ssh -i ~/.ssh/id_rsa git@github.com << 'EOF'
          # Переход в директорию проекта на сервере
          cd //wsl.localhost/Ubuntu/home/kulich/mortgage_calculator 
          # Обновление кода
          git pull origin main
          # Перезапуск сервиса
          systemctl restart your_service
        EOF
