name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
#fgdfgdfgfdg
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Environment
      run: |
        echo "Current User:"
        whoami
        echo "Home Directory:"
        echo $HOME
        echo "Current Directory:"
        pwd
        echo "List of files:"
        ls -la

    - name: Set up SSH
      run: |
        echo "Setting up SSH directory..."
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        echo "Adding private key to SSH..."
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        echo "Adding GitHub to known hosts..."
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts

        echo "Verifying SSH directory:"
        ls -la ~/.ssh

    - name: Deploy to deploy branch
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        echo "Deploying to deploy branch..."
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git config --global user.name "GitHub Actions Bot"
        
        echo "Fetching all branches..."
        git fetch origin

        echo "Checking out deploy branch..."
        git checkout -B deploy

        echo "Pushing changes to deploy branch..."
        git push --force "https://${GITHUB_TOKEN}@github.com/${{ github.repository }}.git" deploy
