name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Выполняется только если тесты прошли успешно
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh

        # Сохранение приватного ключа из GitHub Secrets
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # Добавление GitHub и сервера в список известных хостовdsds
        ssh-keyscan -H github.com >> ~/.ssh/known_hosts
        ssh-keyscan -H localhost >> ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh -tt -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no kulich@172.22.4.126 << 'EOF'
          cd mortgage_calculator
          pkill -f main.py || echo "No running main.py process found."
          nohup python3 /home/kulich/mortgage_calculator/main.py &
        EOF