name: Python CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Debug Environment
      run: |
        whoami
        echo $HOME
        pwd
        ls -la

    - name: Set up SSH
      run: |
        mkdir -p $HOME/.ssh
        chmod 700 $HOME/.ssh
        echo "${{ secrets.DEPLOY_SSH_KEY }}" > $HOME/.ssh/id_rsa
        chmod 600 $HOME/.ssh/id_rsa
        ssh-keyscan -H github.com >> $HOME/.ssh/known_hosts
        ls -la $HOME/.ssh

    - name: Deploy to server
      env:
        GIT_SSH_COMMAND: "ssh -o StrictHostKeyChecking=no"
      run: |
        ssh -i $HOME/.ssh/id_rsa git@github.com << 'EOF'
          cd /kulich/mortgage_calculator
          git pull origin main
          systemctl restart your_service
        EOF
