name: Python CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: sudo apt-get update && sudo apt-get install -y build-essential libyaml-dev

    - name: Upgrade pip, setuptools, and wheel
      run: pip install --upgrade pip setuptools wheel

    - name: Install Cython
      run: pip install cython

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Run tests
      run: pytest